export const routes = {
  home: '/',
  'blobs.store': '/blobs',
  login: '/login',
  register: '/register',
  'password.request': '/password/reset',
  'password.reset': '/password/reset/:token',
  // Public pages
  landing: '/landing',
  'order.form': '/order',
  // Auth-gated app pages
  dashboard: '/dashboard',
  agents: '/agents',
  approvals: '/approvals',
  tickets: '/tickets',
  campaigns: '/campaigns',
  leads: '/leads',
  integrations: '/integrations',
  website: '/website',
  docs: '/documents',
  analytics: '/analytics',
  daily: '/daily-brief',
  onboarding: '/onboarding',
  settings: '/settings',
  'slack.oauth.start': '/slack/oauth/start',
};
